#############################################################################
# Makefile for building: qwit
# Generated by qmake (2.01a) (Qt 4.5.2) on: Sat Aug 22 15:42:52 2009
# Project:  qwit.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile qwit.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DREVISION=\"$(shell svnversion -n .)\" -DVERSION=\"1.0-alpha\" -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Isrc -Ivar -Ivar
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtXml -L/usr/lib64 -L/usr/lib64/qt4 -pthread -pthread -lQtGui -L/usr/X11R6/lib -pthread -lpng -lfreetype -lSM -lICE -pthread -pthread -lXrender -lXrandr -lfontconfig -lXext -lX11 -lQtNetwork -pthread -pthread -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = var/

####### Files

SOURCES       = src/qwit.cpp \
		src/Configuration.cpp \
		src/MainWindow.cpp \
		src/MessageTextEdit.cpp \
		src/OptionsDialog.cpp \
		src/AboutDialog.cpp \
		src/DirectMessageDialog.cpp \
		src/TwitPicDialog.cpp \
		src/AccountConfigurationDialog.cpp \
		src/Account.cpp \
		src/AbstractPage.cpp \
		src/HomePage.cpp \
		src/PublicPage.cpp \
		src/RepliesPage.cpp \
		src/FavoritesPage.cpp \
		src/InboxPage.cpp \
		src/OutboxPage.cpp \
		src/SearchPage.cpp \
		src/TwitterWidget.cpp \
		src/Services.cpp \
		src/Twitter.cpp \
		src/Message.cpp \
		src/QwitTools.cpp \
		src/UserpicsDownloader.cpp \
		src/UrlShortener.cpp \
		src/TwitterWidgetItem.cpp var/moc_MainWindow.cpp \
		var/moc_MessageTextEdit.cpp \
		var/moc_OptionsDialog.cpp \
		var/moc_AboutDialog.cpp \
		var/moc_DirectMessageDialog.cpp \
		var/moc_TwitPicDialog.cpp \
		var/moc_Account.cpp \
		var/moc_AccountConfigurationDialog.cpp \
		var/moc_AbstractPage.cpp \
		var/moc_HomePage.cpp \
		var/moc_PublicPage.cpp \
		var/moc_RepliesPage.cpp \
		var/moc_FavoritesPage.cpp \
		var/moc_InboxPage.cpp \
		var/moc_OutboxPage.cpp \
		var/moc_SearchPage.cpp \
		var/moc_TwitterWidget.cpp \
		var/moc_Twitter.cpp \
		var/moc_QwitTools.cpp \
		var/moc_UserpicsDownloader.cpp \
		var/moc_UrlShortener.cpp \
		var/qrc_qwit.cpp
OBJECTS       = var/qwit.o \
		var/Configuration.o \
		var/MainWindow.o \
		var/MessageTextEdit.o \
		var/OptionsDialog.o \
		var/AboutDialog.o \
		var/DirectMessageDialog.o \
		var/TwitPicDialog.o \
		var/AccountConfigurationDialog.o \
		var/Account.o \
		var/AbstractPage.o \
		var/HomePage.o \
		var/PublicPage.o \
		var/RepliesPage.o \
		var/FavoritesPage.o \
		var/InboxPage.o \
		var/OutboxPage.o \
		var/SearchPage.o \
		var/TwitterWidget.o \
		var/Services.o \
		var/Twitter.o \
		var/Message.o \
		var/QwitTools.o \
		var/UserpicsDownloader.o \
		var/UrlShortener.o \
		var/TwitterWidgetItem.o \
		var/moc_MainWindow.o \
		var/moc_MessageTextEdit.o \
		var/moc_OptionsDialog.o \
		var/moc_AboutDialog.o \
		var/moc_DirectMessageDialog.o \
		var/moc_TwitPicDialog.o \
		var/moc_Account.o \
		var/moc_AccountConfigurationDialog.o \
		var/moc_AbstractPage.o \
		var/moc_HomePage.o \
		var/moc_PublicPage.o \
		var/moc_RepliesPage.o \
		var/moc_FavoritesPage.o \
		var/moc_InboxPage.o \
		var/moc_OutboxPage.o \
		var/moc_SearchPage.o \
		var/moc_TwitterWidget.o \
		var/moc_Twitter.o \
		var/moc_QwitTools.o \
		var/moc_UserpicsDownloader.o \
		var/moc_UrlShortener.o \
		var/qrc_qwit.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qwit.pro
QMAKE_TARGET  = qwit
DESTDIR       = 
TARGET        = qwit

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): var/ui_MainWindow.h var/ui_OptionsDialog.h var/ui_AboutDialog.h var/ui_AccountConfigurationDialog.h var/ui_DirectMessageDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qwit.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtXml.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtNetwork.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile qwit.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtXml.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o Makefile qwit.pro

dist: 
	@$(CHK_DIR_EXISTS) var/qwit1.0.0 || $(MKDIR) var/qwit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) var/qwit1.0.0/ && $(COPY_FILE) --parents src/Configuration.h src/QwitException.h src/MainWindow.h src/MessageTextEdit.h src/OptionsDialog.h src/AboutDialog.h src/DirectMessageDialog.h src/TwitPicDialog.h src/Account.h src/AccountConfigurationDialog.h src/AbstractPage.h src/HomePage.h src/PublicPage.h src/RepliesPage.h src/FavoritesPage.h src/InboxPage.h src/OutboxPage.h src/SearchPage.h src/TwitterWidget.h src/Twitter.h src/Services.h src/Message.h src/QwitTools.h src/UserpicsDownloader.h src/QwitHeaders.h src/UrlShortener.h src/TwitterWidgetItem.h var/qwit1.0.0/ && $(COPY_FILE) --parents qwit.qrc var/qwit1.0.0/ && $(COPY_FILE) --parents src/qwit.cpp src/Configuration.cpp src/MainWindow.cpp src/MessageTextEdit.cpp src/OptionsDialog.cpp src/AboutDialog.cpp src/DirectMessageDialog.cpp src/TwitPicDialog.cpp src/AccountConfigurationDialog.cpp src/Account.cpp src/AbstractPage.cpp src/HomePage.cpp src/PublicPage.cpp src/RepliesPage.cpp src/FavoritesPage.cpp src/InboxPage.cpp src/OutboxPage.cpp src/SearchPage.cpp src/TwitterWidget.cpp src/Services.cpp src/Twitter.cpp src/Message.cpp src/QwitTools.cpp src/UserpicsDownloader.cpp src/UrlShortener.cpp src/TwitterWidgetItem.cpp var/qwit1.0.0/ && $(COPY_FILE) --parents src/MainWindow.ui src/OptionsDialog.ui src/AboutDialog.ui src/AccountConfigurationDialog.ui src/DirectMessageDialog.ui var/qwit1.0.0/ && $(COPY_FILE) --parents translations/qwit_en_US.ts translations/qwit_es_ES.ts translations/qwit_it_IT.ts translations/qwit_pt_BR.ts translations/qwit_ru_RU.ts translations/qwit_kk_KZ.ts translations/qwit_tr_TR.ts var/qwit1.0.0/ && (cd `dirname var/qwit1.0.0` && $(TAR) qwit1.0.0.tar qwit1.0.0 && $(COMPRESS) qwit1.0.0.tar) && $(MOVE) `dirname var/qwit1.0.0`/qwit1.0.0.tar.gz . && $(DEL_FILE) -r var/qwit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: var/moc_MainWindow.cpp var/moc_MessageTextEdit.cpp var/moc_OptionsDialog.cpp var/moc_AboutDialog.cpp var/moc_DirectMessageDialog.cpp var/moc_TwitPicDialog.cpp var/moc_Account.cpp var/moc_AccountConfigurationDialog.cpp var/moc_AbstractPage.cpp var/moc_HomePage.cpp var/moc_PublicPage.cpp var/moc_RepliesPage.cpp var/moc_FavoritesPage.cpp var/moc_InboxPage.cpp var/moc_OutboxPage.cpp var/moc_SearchPage.cpp var/moc_TwitterWidget.cpp var/moc_Twitter.cpp var/moc_QwitTools.cpp var/moc_UserpicsDownloader.cpp var/moc_UrlShortener.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) var/moc_MainWindow.cpp var/moc_MessageTextEdit.cpp var/moc_OptionsDialog.cpp var/moc_AboutDialog.cpp var/moc_DirectMessageDialog.cpp var/moc_TwitPicDialog.cpp var/moc_Account.cpp var/moc_AccountConfigurationDialog.cpp var/moc_AbstractPage.cpp var/moc_HomePage.cpp var/moc_PublicPage.cpp var/moc_RepliesPage.cpp var/moc_FavoritesPage.cpp var/moc_InboxPage.cpp var/moc_OutboxPage.cpp var/moc_SearchPage.cpp var/moc_TwitterWidget.cpp var/moc_Twitter.cpp var/moc_QwitTools.cpp var/moc_UserpicsDownloader.cpp var/moc_UrlShortener.cpp
var/moc_MainWindow.cpp: var/ui_MainWindow.h \
		src/QwitHeaders.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/MessageTextEdit.h \
		src/OptionsDialog.h \
		var/ui_OptionsDialog.h \
		src/AccountConfigurationDialog.h \
		var/ui_AccountConfigurationDialog.h \
		src/AboutDialog.h \
		var/ui_AboutDialog.h \
		src/DirectMessageDialog.h \
		var/ui_DirectMessageDialog.h \
		src/HomePage.h \
		src/RepliesPage.h \
		src/PublicPage.h \
		src/FavoritesPage.h \
		src/InboxPage.h \
		src/OutboxPage.h \
		src/SearchPage.h \
		src/MainWindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/MainWindow.h -o var/moc_MainWindow.cpp

var/moc_MessageTextEdit.cpp: src/QwitHeaders.h \
		src/Message.h \
		src/MessageTextEdit.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/MessageTextEdit.h -o var/moc_MessageTextEdit.cpp

var/moc_OptionsDialog.cpp: var/ui_OptionsDialog.h \
		src/QwitHeaders.h \
		src/AccountConfigurationDialog.h \
		var/ui_AccountConfigurationDialog.h \
		src/Account.h \
		src/Twitter.h \
		src/Message.h \
		src/OptionsDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/OptionsDialog.h -o var/moc_OptionsDialog.cpp

var/moc_AboutDialog.cpp: var/ui_AboutDialog.h \
		src/QwitHeaders.h \
		src/AboutDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/AboutDialog.h -o var/moc_AboutDialog.cpp

var/moc_DirectMessageDialog.cpp: var/ui_DirectMessageDialog.h \
		src/QwitHeaders.h \
		src/DirectMessageDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/DirectMessageDialog.h -o var/moc_DirectMessageDialog.cpp

var/moc_TwitPicDialog.cpp: src/TwitPicDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/TwitPicDialog.h -o var/moc_TwitPicDialog.cpp

var/moc_Account.cpp: src/QwitHeaders.h \
		src/Twitter.h \
		src/Account.h \
		src/Message.h \
		src/Account.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/Account.h -o var/moc_Account.cpp

var/moc_AccountConfigurationDialog.cpp: var/ui_AccountConfigurationDialog.h \
		src/QwitHeaders.h \
		src/AccountConfigurationDialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/AccountConfigurationDialog.h -o var/moc_AccountConfigurationDialog.cpp

var/moc_AbstractPage.cpp: src/QwitHeaders.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/AbstractPage.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/AbstractPage.h -o var/moc_AbstractPage.cpp

var/moc_HomePage.cpp: src/QwitHeaders.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/HomePage.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/HomePage.h -o var/moc_HomePage.cpp

var/moc_PublicPage.cpp: src/QwitHeaders.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/PublicPage.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/PublicPage.h -o var/moc_PublicPage.cpp

var/moc_RepliesPage.cpp: src/QwitHeaders.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/RepliesPage.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/RepliesPage.h -o var/moc_RepliesPage.cpp

var/moc_FavoritesPage.cpp: src/QwitHeaders.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/FavoritesPage.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/FavoritesPage.h -o var/moc_FavoritesPage.cpp

var/moc_InboxPage.cpp: src/QwitHeaders.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/InboxPage.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/InboxPage.h -o var/moc_InboxPage.cpp

var/moc_OutboxPage.cpp: src/QwitHeaders.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/OutboxPage.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/OutboxPage.h -o var/moc_OutboxPage.cpp

var/moc_SearchPage.cpp: src/QwitHeaders.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/SearchPage.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/SearchPage.h -o var/moc_SearchPage.cpp

var/moc_TwitterWidget.cpp: src/QwitHeaders.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/TwitterWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/TwitterWidget.h -o var/moc_TwitterWidget.cpp

var/moc_Twitter.cpp: src/QwitHeaders.h \
		src/Account.h \
		src/Twitter.h \
		src/Message.h \
		src/Twitter.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/Twitter.h -o var/moc_Twitter.cpp

var/moc_QwitTools.cpp: src/QwitHeaders.h \
		src/Message.h \
		src/QwitTools.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/QwitTools.h -o var/moc_QwitTools.cpp

var/moc_UserpicsDownloader.cpp: src/QwitHeaders.h \
		src/UserpicsDownloader.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/UserpicsDownloader.h -o var/moc_UserpicsDownloader.cpp

var/moc_UrlShortener.cpp: src/QwitHeaders.h \
		src/UrlShortener.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/UrlShortener.h -o var/moc_UrlShortener.cpp

compiler_rcc_make_all: var/qrc_qwit.cpp
compiler_rcc_clean:
	-$(DEL_FILE) var/qrc_qwit.cpp
var/qrc_qwit.cpp: qwit.qrc \
		translations/qwit_tr_TR.ts \
		translations/qwit_pt_BR.ts \
		translations/qwit_en_US.ts \
		translations/qwit_es_ES.ts \
		translations/qwit_ru_RU.ts \
		translations/qwit_it_IT.ts \
		translations/qwit_kk_KZ.ts \
		images/about.png \
		images/unfollow.png \
		images/favor.png \
		images/exit.png \
		images/reload.png \
		images/follow.png \
		images/reply.png \
		images/qwit.png \
		images/destroy.png \
		images/twitter.png \
		images/identica.png \
		images/qwitnewmessages.png \
		images/retweet.png \
		images/twitpic.png \
		images/directMessage.png \
		images/options.png
	/usr/bin/rcc -name qwit qwit.qrc -o var/qrc_qwit.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: var/ui_MainWindow.h var/ui_OptionsDialog.h var/ui_AboutDialog.h var/ui_AccountConfigurationDialog.h var/ui_DirectMessageDialog.h
compiler_uic_clean:
	-$(DEL_FILE) var/ui_MainWindow.h var/ui_OptionsDialog.h var/ui_AboutDialog.h var/ui_AccountConfigurationDialog.h var/ui_DirectMessageDialog.h
var/ui_MainWindow.h: src/MainWindow.ui
	/usr/bin/uic src/MainWindow.ui -o var/ui_MainWindow.h

var/ui_OptionsDialog.h: src/OptionsDialog.ui
	/usr/bin/uic src/OptionsDialog.ui -o var/ui_OptionsDialog.h

var/ui_AboutDialog.h: src/AboutDialog.ui
	/usr/bin/uic src/AboutDialog.ui -o var/ui_AboutDialog.h

var/ui_AccountConfigurationDialog.h: src/AccountConfigurationDialog.ui
	/usr/bin/uic src/AccountConfigurationDialog.ui -o var/ui_AccountConfigurationDialog.h

var/ui_DirectMessageDialog.h: src/DirectMessageDialog.ui
	/usr/bin/uic src/DirectMessageDialog.ui -o var/ui_DirectMessageDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

var/qwit.o: src/qwit.cpp src/QwitHeaders.h \
		src/MainWindow.h \
		var/ui_MainWindow.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/MessageTextEdit.h \
		src/OptionsDialog.h \
		var/ui_OptionsDialog.h \
		src/AccountConfigurationDialog.h \
		var/ui_AccountConfigurationDialog.h \
		src/AboutDialog.h \
		var/ui_AboutDialog.h \
		src/DirectMessageDialog.h \
		var/ui_DirectMessageDialog.h \
		src/HomePage.h \
		src/RepliesPage.h \
		src/PublicPage.h \
		src/FavoritesPage.h \
		src/InboxPage.h \
		src/OutboxPage.h \
		src/SearchPage.h \
		src/Services.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/qwit.o src/qwit.cpp

var/Configuration.o: src/Configuration.cpp src/QwitHeaders.h \
		src/MainWindow.h \
		var/ui_MainWindow.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/MessageTextEdit.h \
		src/OptionsDialog.h \
		var/ui_OptionsDialog.h \
		src/AccountConfigurationDialog.h \
		var/ui_AccountConfigurationDialog.h \
		src/AboutDialog.h \
		var/ui_AboutDialog.h \
		src/DirectMessageDialog.h \
		var/ui_DirectMessageDialog.h \
		src/HomePage.h \
		src/RepliesPage.h \
		src/PublicPage.h \
		src/FavoritesPage.h \
		src/InboxPage.h \
		src/OutboxPage.h \
		src/SearchPage.h \
		src/Services.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/Configuration.o src/Configuration.cpp

var/MainWindow.o: src/MainWindow.cpp src/QwitHeaders.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/MainWindow.h \
		var/ui_MainWindow.h \
		src/AbstractPage.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/MessageTextEdit.h \
		src/OptionsDialog.h \
		var/ui_OptionsDialog.h \
		src/AccountConfigurationDialog.h \
		var/ui_AccountConfigurationDialog.h \
		src/AboutDialog.h \
		var/ui_AboutDialog.h \
		src/DirectMessageDialog.h \
		var/ui_DirectMessageDialog.h \
		src/HomePage.h \
		src/RepliesPage.h \
		src/PublicPage.h \
		src/FavoritesPage.h \
		src/InboxPage.h \
		src/OutboxPage.h \
		src/SearchPage.h \
		src/UserpicsDownloader.h \
		src/TwitPicDialog.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/MainWindow.o src/MainWindow.cpp

var/MessageTextEdit.o: src/MessageTextEdit.cpp src/QwitHeaders.h \
		src/MessageTextEdit.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/MessageTextEdit.o src/MessageTextEdit.cpp

var/OptionsDialog.o: src/OptionsDialog.cpp src/QwitHeaders.h \
		src/MainWindow.h \
		var/ui_MainWindow.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/MessageTextEdit.h \
		src/OptionsDialog.h \
		var/ui_OptionsDialog.h \
		src/AccountConfigurationDialog.h \
		var/ui_AccountConfigurationDialog.h \
		src/AboutDialog.h \
		var/ui_AboutDialog.h \
		src/DirectMessageDialog.h \
		var/ui_DirectMessageDialog.h \
		src/HomePage.h \
		src/RepliesPage.h \
		src/PublicPage.h \
		src/FavoritesPage.h \
		src/InboxPage.h \
		src/OutboxPage.h \
		src/SearchPage.h \
		src/Services.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/OptionsDialog.o src/OptionsDialog.cpp

var/AboutDialog.o: src/AboutDialog.cpp src/QwitHeaders.h \
		src/AboutDialog.h \
		var/ui_AboutDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/AboutDialog.o src/AboutDialog.cpp

var/DirectMessageDialog.o: src/DirectMessageDialog.cpp src/QwitHeaders.h \
		src/DirectMessageDialog.h \
		var/ui_DirectMessageDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/DirectMessageDialog.o src/DirectMessageDialog.cpp

var/TwitPicDialog.o: src/TwitPicDialog.cpp src/TwitPicDialog.h \
		src/Configuration.h \
		src/QwitHeaders.h \
		src/Account.h \
		src/Twitter.h \
		src/Message.h \
		src/UrlShortener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/TwitPicDialog.o src/TwitPicDialog.cpp

var/AccountConfigurationDialog.o: src/AccountConfigurationDialog.cpp src/QwitHeaders.h \
		src/AccountConfigurationDialog.h \
		var/ui_AccountConfigurationDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/AccountConfigurationDialog.o src/AccountConfigurationDialog.cpp

var/Account.o: src/Account.cpp src/QwitHeaders.h \
		src/Account.h \
		src/Twitter.h \
		src/Message.h \
		src/QwitTools.h \
		src/Configuration.h \
		src/UrlShortener.h \
		src/Services.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/Account.o src/Account.cpp

var/AbstractPage.o: src/AbstractPage.cpp src/QwitHeaders.h \
		src/MainWindow.h \
		var/ui_MainWindow.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/MessageTextEdit.h \
		src/OptionsDialog.h \
		var/ui_OptionsDialog.h \
		src/AccountConfigurationDialog.h \
		var/ui_AccountConfigurationDialog.h \
		src/AboutDialog.h \
		var/ui_AboutDialog.h \
		src/DirectMessageDialog.h \
		var/ui_DirectMessageDialog.h \
		src/HomePage.h \
		src/RepliesPage.h \
		src/PublicPage.h \
		src/FavoritesPage.h \
		src/InboxPage.h \
		src/OutboxPage.h \
		src/SearchPage.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/AbstractPage.o src/AbstractPage.cpp

var/HomePage.o: src/HomePage.cpp src/QwitHeaders.h \
		src/HomePage.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/HomePage.o src/HomePage.cpp

var/PublicPage.o: src/PublicPage.cpp src/QwitHeaders.h \
		src/PublicPage.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/PublicPage.o src/PublicPage.cpp

var/RepliesPage.o: src/RepliesPage.cpp src/QwitHeaders.h \
		src/RepliesPage.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/RepliesPage.o src/RepliesPage.cpp

var/FavoritesPage.o: src/FavoritesPage.cpp src/QwitHeaders.h \
		src/FavoritesPage.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/FavoritesPage.o src/FavoritesPage.cpp

var/InboxPage.o: src/InboxPage.cpp src/QwitHeaders.h \
		src/InboxPage.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/InboxPage.o src/InboxPage.cpp

var/OutboxPage.o: src/OutboxPage.cpp src/QwitHeaders.h \
		src/OutboxPage.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/OutboxPage.o src/OutboxPage.cpp

var/SearchPage.o: src/SearchPage.cpp src/QwitHeaders.h \
		src/SearchPage.h \
		src/AbstractPage.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h \
		src/QwitTools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/SearchPage.o src/SearchPage.cpp

var/TwitterWidget.o: src/TwitterWidget.cpp src/QwitHeaders.h \
		src/TwitterWidget.h \
		src/TwitterWidgetItem.h \
		src/Message.h \
		src/QwitException.h \
		src/QwitTools.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/TwitterWidget.o src/TwitterWidget.cpp

var/Services.o: src/Services.cpp src/QwitHeaders.h \
		src/Services.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/Services.o src/Services.cpp

var/Twitter.o: src/Twitter.cpp src/QwitHeaders.h \
		src/Twitter.h \
		src/Account.h \
		src/Message.h \
		src/QwitTools.h \
		src/Services.h \
		src/Configuration.h \
		src/UrlShortener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/Twitter.o src/Twitter.cpp

var/Message.o: src/Message.cpp src/QwitHeaders.h \
		src/QwitTools.h \
		src/Message.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/Message.o src/Message.cpp

var/QwitTools.o: src/QwitTools.cpp src/QwitHeaders.h \
		src/QwitTools.h \
		src/Message.h \
		src/UserpicsDownloader.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/UrlShortener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/QwitTools.o src/QwitTools.cpp

var/UserpicsDownloader.o: src/UserpicsDownloader.cpp src/QwitHeaders.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/Message.h \
		src/UrlShortener.h \
		src/UserpicsDownloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/UserpicsDownloader.o src/UserpicsDownloader.cpp

var/UrlShortener.o: src/UrlShortener.cpp src/UrlShortener.h \
		src/QwitHeaders.h \
		src/Configuration.h \
		src/Account.h \
		src/Twitter.h \
		src/Message.h \
		src/Services.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/UrlShortener.o src/UrlShortener.cpp

var/TwitterWidgetItem.o: src/TwitterWidgetItem.cpp src/QwitHeaders.h \
		src/QwitTools.h \
		src/Message.h \
		src/TwitterWidgetItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/TwitterWidgetItem.o src/TwitterWidgetItem.cpp

var/moc_MainWindow.o: var/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_MainWindow.o var/moc_MainWindow.cpp

var/moc_MessageTextEdit.o: var/moc_MessageTextEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_MessageTextEdit.o var/moc_MessageTextEdit.cpp

var/moc_OptionsDialog.o: var/moc_OptionsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_OptionsDialog.o var/moc_OptionsDialog.cpp

var/moc_AboutDialog.o: var/moc_AboutDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_AboutDialog.o var/moc_AboutDialog.cpp

var/moc_DirectMessageDialog.o: var/moc_DirectMessageDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_DirectMessageDialog.o var/moc_DirectMessageDialog.cpp

var/moc_TwitPicDialog.o: var/moc_TwitPicDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_TwitPicDialog.o var/moc_TwitPicDialog.cpp

var/moc_Account.o: var/moc_Account.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_Account.o var/moc_Account.cpp

var/moc_AccountConfigurationDialog.o: var/moc_AccountConfigurationDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_AccountConfigurationDialog.o var/moc_AccountConfigurationDialog.cpp

var/moc_AbstractPage.o: var/moc_AbstractPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_AbstractPage.o var/moc_AbstractPage.cpp

var/moc_HomePage.o: var/moc_HomePage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_HomePage.o var/moc_HomePage.cpp

var/moc_PublicPage.o: var/moc_PublicPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_PublicPage.o var/moc_PublicPage.cpp

var/moc_RepliesPage.o: var/moc_RepliesPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_RepliesPage.o var/moc_RepliesPage.cpp

var/moc_FavoritesPage.o: var/moc_FavoritesPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_FavoritesPage.o var/moc_FavoritesPage.cpp

var/moc_InboxPage.o: var/moc_InboxPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_InboxPage.o var/moc_InboxPage.cpp

var/moc_OutboxPage.o: var/moc_OutboxPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_OutboxPage.o var/moc_OutboxPage.cpp

var/moc_SearchPage.o: var/moc_SearchPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_SearchPage.o var/moc_SearchPage.cpp

var/moc_TwitterWidget.o: var/moc_TwitterWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_TwitterWidget.o var/moc_TwitterWidget.cpp

var/moc_Twitter.o: var/moc_Twitter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_Twitter.o var/moc_Twitter.cpp

var/moc_QwitTools.o: var/moc_QwitTools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_QwitTools.o var/moc_QwitTools.cpp

var/moc_UserpicsDownloader.o: var/moc_UserpicsDownloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_UserpicsDownloader.o var/moc_UserpicsDownloader.cpp

var/moc_UrlShortener.o: var/moc_UrlShortener.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/moc_UrlShortener.o var/moc_UrlShortener.cpp

var/qrc_qwit.o: var/qrc_qwit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o var/qrc_qwit.o var/qrc_qwit.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/local/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install_desktop: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/share/applications/ 
	-$(INSTALL_FILE) /home/arti/Projects/code.google.com/qwit/branches/ng/qwit.desktop $(INSTALL_ROOT)/usr/local/share/applications/


uninstall_desktop:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/applications/qwit.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/applications/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/share/icons/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/share/icons/ 
	-$(INSTALL_FILE) /home/arti/Projects/code.google.com/qwit/branches/ng/images/qwit.png $(INSTALL_ROOT)/usr/local/share/icons/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/icons/qwit.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/icons/ 


install:  install_target install_desktop install_icon  FORCE

uninstall: uninstall_target uninstall_desktop uninstall_icon   FORCE

FORCE:

